### PR TITLE
(PE-20023) Update beaker answers for Hoyt

### PR DESCRIPTION
**Pull request by demophoon**
This PR contains the code for beaker to start generating answers for the Hoyt builds of PE.

### CODE REVIEW

**Comment by jpartlow** [comment]
Would you add a basic spec, similar to 2017.2, I think just a test of mono 1.0 and mono 2.0 is fine.

**Comment by demophoon** [comment]
@jpartlow Spec added.

**Comment by tvpartytonight** [comment]
👍

**Comment by jpartlow** [comment]
Specs pass locally.

**Pull request merged**
