### PR TITLE
(PE-25203) Update beaker-answers for PE 2019.1.x

### PR DESCRIPTION
**Pull request by barriserloth**
This commit adds an updated version file for PE 2019.1

### CODE REVIEW

**Comment by cthorn42** [comment]
jenkins please retest this

**Comment by cthorn42** [comment]
jenkins test this please

**Comment by highb** [comment]
This needs more test coverage to pass.

**Comment by kevpl** [comment]
figured out the simplecov issue, fix was merged from #47.

retest this please

**Pull request merged**
