### PR TITLE
PE-27373 Update for 2019.3.x

### PR DESCRIPTION
**Pull request by shaigy**
Add beaker-answers for 2019.3.x

### CODE REVIEW

**Comment by kevpl** [comment]
It looks like we haven't added any new implementation code to these versions [since 2017.2](https://github.com/puppetlabs/beaker-answers/blob/master/lib/beaker-answers/versions/version20172.rb) and that most of our beaker-answer's version files are just the number checks.

That makes me think that changes to this repo are often done as reactions when a new version is made & a failure is caused by not having beaker-answers support that version. We've done this dance enough that I'm thinking now might be the time to get out ahead of the problem & develop a strategy for defaulting when we see a version number that we don't recognize.

One idea for this would be to add a wider "bucket" version check to the first version of every year. So for example, this year's [first version (2019.0)](https://github.com/puppetlabs/beaker-answers/blob/master/lib/beaker-answers/versions/version20190.rb) has this check for exact version match:
```ruby
    # The version of PE that this set of answers is appropriate for
    def self.pe_version_matcher
      /\A2019\.0/
    end
```
but it could also have a more generic matcher that could be a fallback, so that if it doesn't match any versions `pe_version_matcher` exactly, it could match one of those & get the defaults from there:
```ruby
    def self.pe_default_matcher
      /\A2019\.\d/
    end
```
(disclosure: don't remember the regex syntax off-the-top, so that probably won't work copied). As long as beaker-answers _loudly_ announces what it's defaulting to when it executes (perhaps even spewing the entire thing out to the console if we think that'd be helpful for Root Cause Analysis), this seems like it might have a small advantage over failing the first number of tests while we work through these kinds of issues.

What do you think? I imagine with some of your time, installer team could find a better solution to this issue than the one proposed above. Also, would you mind putting the reason that the PR is set _do not merge_ in a comment here?

**Comment by kevpl** [comment]
Hi @shaigy. I know you're busy, and the larger question of my comment isn't urgent (a long term solution doesn't need to be figured out here), but would you mind commenting as to why this is set _do not merge_?

**Comment by shaigy** [comment]
@kevpl Sorry, I was waiting for the 2019.3 branches to be up which now I think of it is not a requirement for this change to go in. I removed the DNM label. Feel free to merge whenever you get time

**Comment by shaigy** [comment]
@kevpl I don't know whether this is a real problem or not. One thing that came to mind is, with a default matcher like '/\A2019\.\d/' all of the 2019.x will match to that version and in that case, will it be able to update the answers for a specific version say 2019.4? May be this is not needed, but just a thought. I am going to check with the team and see what everyone thinks and if anyone has better idea.

**Comment by cthorn42** [comment]
@puppetlabs/qe-team Can we get someone to merge this?

**Comment by highb** [comment]
Created #56 to kill this toil.

**Pull request merged**
