### PR TITLE
Add Dependabot to keep thins up to date

### PR DESCRIPTION
**Pull request by genebean**

### CODE REVIEW

**Comment by genebean** [comment]
The failure here looks to be because Ruby 2.3 is used in jjb and that is too old for some of the gems being installed.

**Comment by shaigy** [comment]
@genebean Here is the PR to update ruby version
https://github.com/puppetlabs/ci-job-configs/pull/7143

**Comment by genebean** [comment]
Jenkins retest this please

**Comment by genebean** [comment]
@shaigy looks like that fixed it :)

**Comment by shaigy** [comment]
👍

**Pull request merged**
