### PR TITLE
(PE-12849) Add q_use_application_services to console

### PR DESCRIPTION
**Pull request by highb**
Both the master and console must be given the
`q_use_application_services` answer, since the console
needs to know that it needs classify the orchestrator.

### CODE REVIEW

**Comment by ericwilliamson** [comment]
@demophoon :magic: - https://github.com/puppetlabs/beaker/blob/master/lib/beaker/dsl/install_utils/pe_utils.rb#L427-L428

**Comment by ericwilliamson** [comment]
oh jk - https://github.com/puppetlabs/beaker-answers/pull/8/files#diff-eff08577f1b8bf65d16337a50c4b118aR18 - looks like it needs to be added

**Comment by demophoon** [comment]
@ericwilliamson but.. but.. but.. but..... https://github.com/highb/beaker-answers/blob/maint/app_services_on_console/lib/beaker-answers/versions/version20153.rb#L18

**Comment by highb** [comment]
Oh right, it's... dashboard?

**Comment by highb** [comment]
Oh it just doesn't exist. Fuuuu

**Comment by ericwilliamson** [comment]
ok to test

**Comment by ericwilliamson** [comment]
:+1: just waiting on jenkins to thumbs up

/cc @puppetlabs/beaker

**Comment by ericwilliamson** [comment]
test this please

**Comment by highb** [comment]
retest this please?

**Comment by highb** [comment]
@ericwilliamson I don't think it's going to re-test this. `be rspec` runs fine for me, though.

**Comment by ericwilliamson** [comment]
test this please

**Comment by ericwilliamson** [comment]
@highb I didn't add myself to the right whitelist, it should run now

**Comment by highb** [comment]
Woohoo!

**Comment by rick** [comment]
:+1:

**Pull request merged**
